# Generated by Django 4.2.8 on 2026-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_date_joined_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
