# Generated by Django 4.2.8 on 2025-12-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_start_time', models.TimeField(default='09:00:00', help_text='Office start time (e.g., 09:00)')),
                ('office_end_time', models.TimeField(default='17:00:00', help_text='Office end time (e.g., 17:00)')),
                ('late_threshold_minutes', models.IntegerField(default=15, help_text='Minutes after start time to mark as late')),
                ('working_days', models.CharField(default='1,2,3,4,5', help_text='Comma-separated weekday numbers (0=Monday, 6=Sunday)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
