# Generated by Django 4.2.8 on 2026-06-15 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_allownace_allowance_employeeallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxslab',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.fiscalyear'),
        ),
    ]
