# Generated by Django 4.2.8 on 2026-06-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_taxslab_fiscal_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundstype',
            old_name='org_comntribution',
            new_name='org_contribution',
        ),
    ]
