# Generated by Django 4.2.8 on 2026-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rename_org_comntribution_fundstype_org_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='days_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='early_departures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='earned_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='effective_working_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_arrivals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='leave_days_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='missing_checkouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='three_late_arrivals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='three_late_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='unpaid_absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='fine_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
