# Generated by Django 4.2.8 on 2026-06-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_payroll_allowance_payroll_base_salary_payroll_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
