# Generated by Django 4.2.8 on 2026-06-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auditlog_content_type_auditlog_modeule_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='modeule_name',
            new_name='module_name',
        ),
    ]
