# Generated by Django 4.2.8 on 2026-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rename_modeule_name_auditlog_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
