# Generated by Django 4.2.8 on 2026-06-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_basic_salary_employee_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
