# Generated by Django 4.2.8 on 2026-06-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_taxslab_fiscal_year'),
        ('employees', '0005_alter_employee_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.allowance'),
        ),
    ]
