# Generated by Django 4.2.8 on 2025-12-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField(default=4370)),
                ('password', models.IntegerField(default=0)),
                ('timeout', models.IntegerField(default=5, help_text='Connection timeout in seconds')),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_connection_status', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'biometric_devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('USER_PUSH', 'User Push to Device'), ('USER_PULL', 'User Pull from Device'), ('ATTENDANCE_PULL', 'Attendance Pull from Device'), ('DEVICE_INFO', 'Device Info Fetch')], max_length=20)),
                ('status', models.CharField(choices=[('SU', 'Success'), ('FA', 'Failed'), ('PA', 'Partial')], max_length=2)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_success', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='biometric.biometricdevice')),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['sync_type', 'status'], name='sync_logs_sync_ty_e75e61_idx'), models.Index(fields=['started_at'], name='sync_logs_started_2c7a3f_idx')],
            },
        ),
    ]
