# Generated by Django 4.2.8 on 2025-12-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField(db_index=True)),
                ('punch_type', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out'), ('BREAK_OUT', 'Break Out'), ('BREAK_IN', 'Break In')], default='IN', max_length=10)),
                ('biometric_user_id', models.IntegerField(help_text='UID from biometric device')),
                ('device_id', models.CharField(blank=True, help_text='Device serial number', max_length=50)),
                ('punch_state', models.IntegerField(blank=True, help_text='Punch state from device', null=True)),
                ('verify_type', models.IntegerField(blank=True, help_text='Verification type from device', null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('is_manual', models.BooleanField(default=False, help_text='Manually added record')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-punch_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_work_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('grace_period_minutes', models.IntegerField(default=15, help_text='Grace period for late arrival')),
                ('shift_start_time', models.TimeField(default='09:00:00')),
                ('shift_end_time', models.TimeField(default='17:00:00')),
                ('lunch_break_duration', models.IntegerField(default=60, help_text='Lunch break in minutes')),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('half_day_threshold_hours', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
                'db_table': 'attendance_settings',
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PR', 'Present'), ('AB', 'Absent'), ('HL', 'Half Day'), ('LT', 'Late'), ('LV', 'On Leave'), ('WO', 'Week Off'), ('HO', 'Holiday')], default='AB', max_length=2)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_break_time', models.DecimalField(decimal_places=2, default=0.0, help_text='Total break time in hours', max_digits=5)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_departure', models.BooleanField(default=False)),
                ('is_overtime', models.BooleanField(default=False)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'daily_attendance',
                'ordering': ['-date'],
            },
        ),
    ]
